const Test1 = [{
    prompt: "1. Polițistul are dreptul la o compensație pentru chirie de până la:",
    optionA: "a) 100% din salariul de bază",
    optionB: "b) 70% din salariul de bază",
    optionC: "c) 50% din salariul de bază",
    optionD: "d) 30% din salariul de bază",
    answer: "C",
    explanation:"*Explicatie",
},
{
    prompt: "2. Constituie contravenție: ",
    optionA: "a) alungarea din locuinţa comună a soţului sau soţiei, cu excepția descoperirii unui adulter",
    optionB: "b) provocarea ori participarea efectivă la scandal",
    optionC: "c) alarmarea publicului pentru a interveni în caz de pericol, prin darea semnalelor de pericol, fără motiv întemeiat",
    optionD: "d) lăsarea în libertate ori fără supraveghere a animalelor",
    answer: "C",
    explanation:"*Explicatie",
},
{
    prompt: "3. Camera Deputaților și Senatul sunt alese prin vot:",
    optionA: "a) universal, liber exprimat, secret, direct, egal",
    optionB: "b) universal, secret, direct, egal",
    optionC: "c) universal, liber exprimat, direct, egal",
    optionD: "d) universal, liber exprimat, secret, direct, egal, neviciat",
    answer: "A",
    explanation:"*Explicatie",
},
{
    prompt: "4. În cazul polițistului, după pensionare, armamentul dobândit personal",
    optionA: "a) se depune la secția de poliție în a cărei rază se află domiciuliul",
    optionB: "b) se depune la secția de poliție în a cărei rază se află reședința",
    optionC: "c) se deține, în baza permisului obținut",
    optionD: "d) se deține, nefiind necesar permisul port-armă",
    answer: "C",
    explanation:"*Explicatie",
},
{
    prompt: "5. Acordarea zilelor de odihnă săptămânale ce se cuvin polițistului poate fi amânată, în mod excepțional, cel mult de două ori într-o lună:",
    optionA: "a) dacă se instituie stare de urgență, de asediu, de mobilizare sau de război",
    optionB: "b) în situații de catastrofe, calamități, tulburări de amploare ale ordinii și liniștii publice",
    optionC: "c) doar în situația stării de urgență sau de asediu",
    optionD: "d) dacă interesele serviciului o impun",
    answer: "D",
    explanation:"*Explicatie",
},
{
    prompt: "6. Nu constituie venituri ale Corpului Național al Polițiștilor:",
    optionA: "a) taxa de înscriere, cotizaţii lunare ale membrilor, alte venituri realizate din manifestări ştiinţifice, culturale şi sportive, precum şi din drepturi editoriale",
    optionB: "b) resurse obţinute de la bugetul de stat şi/sau bugetele locale",
    optionC: "c) donaţii şi sponsorizări din partea unor persoane fizice sau juridice, din ţara ori din străinătate, în condiţiile legii şi ale normelor instituite de ministrul afacerilor interne",
    optionD: "d) chiriile personale obținute de către membrii Corpului Național al Polițiștilor",
    answer: "D",
    explanation:"*Explicatie",
},
{
    prompt: "7. Constituie contravenție, potrivit Legii nr. 61 din 27 septembrie 1991 pentru sancționarea faptelor de încălcare a unor norme de conviețuire socială, a ordinii și liniștii publice, republicată, cu modificările și completările ulterioare, următoarea faptă:",
    optionA: "a) neluarea măsurilor de prevenire a atacului canin de către proprietarul sau deținătorul temporar al câinelui, dacă fapta s-a soldat cu rănirea sau cu uciderea unui animal domestic",
    optionB: "b) organizarea luptelor între câini, antrenarea câinilor în acest scop și participarea cu câini la astfel de lupte, indiferent cărei rase îi aparțin câinii",
    optionC: "c) atragerea de persoane, sub orice formă, săvârşită în localuri, parcuri, pe străzi sau în alte locuri publice în vederea practicării de raporturi sexuale cu acestea spre a obţine foloase materiale, precum şi îndemnul sau determinarea, în acelaşi scop, a unei persoane la săvârşirea unor astfel de fapte",
    optionD: "d) toate variantele sunt corecte",
    answer: "C",
    explanation:"*Explicatie",
},
{
    prompt: "8. Mandatul Președintelui României este de:",
    optionA: "a) 4 ani",
    optionB: "b) 5 ani",
    optionC: "c) 6 ani",
    optionD: "d) 7 ani",
    answer: "B",
    explanation:"*Explicatie",
},
{
    prompt: "9. Polițistul este:",
    optionA: "a) funcţionarul public cu statut special, care exercită atribuţiile stabilite de lege pentru poliţia română şi celelalte structuri poliţieneşti din Ministerul Administraţiei şi Internelor",
    optionB: "b) funcţionarul public civil cu statut special, care exercită atribuţiile stabilite de lege pentru poliţia română şi celelalte structuri poliţieneşti din Ministerul Administraţiei şi Internelor",
    optionC: "c) funcţionarul civil cu statut special, care exercită atribuţiile stabilite de lege pentru poliţia română şi celelalte structuri poliţieneşti din Ministerul Administraţiei şi Internelor",
    optionD: "d) funcţionarul public civil , care exercită atribuţiile stabilite de lege pentru poliţia română şi celelalte structuri poliţieneşti din Ministerul Administraţiei şi Internelor",
    answer: "B",
    explanation:"*Explicatie",
},
{
    prompt: "10: Contravențiile pot fi constatate și de către:",
    optionA: "a) primar",
    optionB: "b) preot",
    optionC: "c) medic",
    optionD: "d) gardian",
    answer: "A",
    explanation:"*Explicatie",
}
]

export const Questions = [Test1]